# Introdução ao `numpy`

In [61]:
import numpy as np
import matplotlib.pyplot as plt  # Biblioteca para gerar gráficos

Vamos criar umas matrizes e vetores para começar...

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\ &
\boldsymbol{B} &= \begin{bmatrix}1 & 3\\ 5 & 7\end{bmatrix}\\\\
\boldsymbol{v}_1 &= \begin{bmatrix}5 & 3\end{bmatrix}\ &
\boldsymbol{v}_2 &= \begin{bmatrix}9 & 2 & 1\end{bmatrix}
\end{aligned}$$

In [62]:
A = np.array([[2,0],[4,6],[8,2]])
B = np.array([[1,3],[5,7]])
v1 = np.array([5,3])
v2 = np.array([9,2,1])

In [63]:
print("Dimensão de A:", A.shape)
print("Dimensão de B:", B.shape)
print("Dimensão de v1:", v1.shape)
print("Dimensão de v2:", v2.shape)

Dimensão de A: (3, 2)
Dimensão de B: (2, 2)
Dimensão de v1: (2,)
Dimensão de v2: (3,)


$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\boldsymbol{A}^{\top} &= \begin{bmatrix}2 & 4 & 8\\ 0 & 6 & 2\end{bmatrix}
\end{aligned}$$

In [64]:
print("Matriz original:")
print(A)
print("Matriz transposta:")
print(A.T)

Matriz original:
[[2 0]
 [4 6]
 [8 2]]
Matriz transposta:
[[2 4 8]
 [0 6 2]]


$$\begin{aligned}
\boldsymbol{A}[0] &= \begin{bmatrix}2 & 0\end{bmatrix}\\
\boldsymbol{A}[[0,2]] &= \begin{bmatrix}2 & 0\\ 8 & 2\end{bmatrix}\\
\end{aligned}$$

In [65]:
print("Primeira linha de A:")
print(A[0], "dimensão:", A[0].shape) # Primeira linha de A
print("Primeira e terceira linha de A:")
print(A[[0,2]], "dimensão:", A[[0,2]].shape) # Primeira e terceira linha de A
print("Primeira linha de A (mantendo 2 dimensões):")
print(A[[0]], "dimensão:", A[[0]].shape) # Primeira linha de A (mantendo 2 dimensões)

Primeira linha de A:
[2 0] dimensão: (2,)
Primeira e terceira linha de A:
[[2 0]
 [8 2]] dimensão: (2, 2)
Primeira linha de A (mantendo 2 dimensões):
[[2 0]] dimensão: (1, 2)


In [66]:
A

array([[2, 0],
       [4, 6],
       [8, 2]])

$$\begin{aligned}
\boldsymbol{A}[:,0] &= \begin{bmatrix}2 & 4 & 8\end{bmatrix}\\
\boldsymbol{A}[:,[0]] &= \begin{bmatrix}2 \\ 4 \\ 8\end{bmatrix}
\end{aligned}$$

In [67]:
print("Primeira coluna do A:")
print(A[:,0], "dimensão:", A[:,0].shape) # Primeira coluna do A
print("Primeira e segunda coluna do A:")
print(A[:,[0,1]], "dimensão:", A[:,[0,1]].shape) # Primeira e segunda coluna do A
print("Primeira coluna do A (mantendo 2 dimensões):")
print(A[:,[0]], "dimensão:", A[:,[0]].shape) # Primeira coluna do A (mantendo 2 dimensões)

Primeira coluna do A:
[2 4 8] dimensão: (3,)
Primeira e segunda coluna do A:
[[2 0]
 [4 6]
 [8 2]] dimensão: (3, 2)
Primeira coluna do A (mantendo 2 dimensões):
[[2]
 [4]
 [8]] dimensão: (3, 1)


$$\begin{aligned}
\left[\begin{bmatrix}2 & 4 & 8\end{bmatrix}; \begin{bmatrix}1 & 2 & 3\end{bmatrix}\right] &= \begin{bmatrix}2 & 4 & 8\\1 & 2 & 3\end{bmatrix}\\
\left[\begin{bmatrix}2 \\ 4 \\ 8\end{bmatrix}, \begin{bmatrix}1 \\ 2 \\ 3\end{bmatrix}\right] &= \begin{bmatrix}2 & 1 \\ 4 & 2 \\ 8 & 3\end{bmatrix}
\end{aligned}$$

In [68]:
a = np.array([2, 4, 8]).reshape((1,-1))
b = np.array([1, 2, 3]).reshape((1,-1))
ab = np.r_[a,b]

print(a, "dimensão:", a.shape)
print(b, "dimensão:", b.shape)
print(ab, "dimensão:", ab.shape) # row stack

[[2 4 8]] dimensão: (1, 3)
[[1 2 3]] dimensão: (1, 3)
[[2 4 8]
 [1 2 3]] dimensão: (2, 3)


In [69]:
np.vstack((a,b))

array([[2, 4, 8],
       [1, 2, 3]])

In [70]:
a = a.reshape((-1, 1))

In [71]:
c = np.array([2, 4, 8]).reshape((-1,1))
d = np.array([1, 2, 3]).reshape((-1,1))
cd = np.c_[c,d]

print(c, "dimensão:", c.shape)
print(d, "dimensão:", d.shape)
print(cd, "dimensão:", cd.shape) # column stack

[[2]
 [4]
 [8]] dimensão: (3, 1)
[[1]
 [2]
 [3]] dimensão: (3, 1)
[[2 1]
 [4 2]
 [8 3]] dimensão: (3, 2)


In [72]:
np.hstack((c,d))

array([[2, 1],
       [4, 2],
       [8, 3]])

## Matrizes notáveis

$$\begin{aligned}
\boldsymbol{I}_n = \mathtt{np.eye(n)} &= \begin{bmatrix}1 & 0 & \ldots\\ 0 & 1 & \ldots\\ \vdots&\vdots&\vdots\\ 0 & \ldots & 1\end{bmatrix}&
\boldsymbol{0}_{n,m} = \mathtt{np.zeros((n,m))} &= \begin{bmatrix}0 & 0 & \ldots\\ 0 & 0 & \ldots\\ \vdots&\vdots&\vdots\\ 0 & \ldots & 0\end{bmatrix}\\
\boldsymbol{1}_{n,m} = \mathtt{np.ones((n,m))} &= \begin{bmatrix}1 & 1 & \ldots\\ 1 & 1 & \ldots\\ \vdots&\vdots&\vdots\\ 1 & \ldots & 1\end{bmatrix}\\
\end{aligned}$$

In [73]:
print("Matriz identidade de ordem 5:")
print(np.eye(5))
print("Matriz de zeros 5x3:")
print(np.zeros((6,3)))
print("Matriz de uns 3x1:")
print(np.ones((3,8)))

Matriz identidade de ordem 5:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Matriz de zeros 5x3:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriz de uns 3x1:
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


Além dessas matrizes notáveis, também podemos fazer matrizes aleatórias:

`np.random.rand(n,m)` é uma matrix $n$ por $m$ onde $[\mathtt{np.random.rand(n,m)}]_{ij} \sim \mathcal{U}(0,1)$.

Ou seja, $[\mathtt{np.random.rand(n,m)}]_{ij} \in [0,1)$

`np.random.randn(n,m)` é uma matrix $n$ por $m$ onde $[\mathtt{np.random.randn(n,m)}]_{ij} \sim \mathcal{N}(0,1)$

Ou seja, $[\mathtt{np.random.randn(n,m)}]_{ij} \in (-\infty,+\infty)$

In [74]:
print("Matriz 5x3 de números aleatórios amostrados de U(0,1):")
print(np.random.rand(5,3))
print("Matriz 2x2 de números aleatórios amostrados de N(0,1):")
print(np.random.randn(2,2))

Matriz 5x3 de números aleatórios amostrados de U(0,1):
[[0.31767066 0.58990495 0.34830325]
 [0.16435893 0.30542339 0.26637923]
 [0.19017881 0.33724153 0.11215676]
 [0.06412566 0.3543718  0.72145735]
 [0.11256191 0.23809295 0.28222141]]
Matriz 2x2 de números aleatórios amostrados de N(0,1):
[[-0.99682743 -3.14490825]
 [-0.7185218  -0.36334626]]


## Operações lineares

Produto de escalares por matrizes:
$$\begin{aligned}
5\boldsymbol{A} &= \begin{bmatrix}2\cdot 5 & 0\cdot 5\\ 4\cdot 5 & 6\cdot 5\\ 8\cdot 5 & 2\cdot 5\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}10 & 0\\ 20 & 30\\ 40 & 10\end{bmatrix}
\end{aligned}$$

In [75]:
print(5 * A)

[[10  0]
 [20 30]
 [40 10]]


Soma de matrizes:
$$\begin{aligned}
\boldsymbol{A}+\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}+\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}4 & 0\\ 8 & 12\\ 26 & 4\end{bmatrix}
\end{aligned}$$

In [76]:
print(A + A)

[[ 4  0]
 [ 8 12]
 [16  4]]


Produto com broadcast (difusão) de um vetor por uma matriz:
$$\begin{aligned}
\boldsymbol{v}_1 \bullet \boldsymbol{A} &= \begin{bmatrix}5 & 3\end{bmatrix}\bullet\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}5\cdot 2 & 3\cdot 0\\ 5\cdot 4 & 3\cdot 6\\ 5\cdot 8 & 3\cdot 2\end{bmatrix}\\
&= \begin{bmatrix}10 & 0\\ 20 & 18\\ 40 & 6\end{bmatrix}\\
\end{aligned}$$

In [77]:
print(v1 * A)

[[10  0]
 [20 18]
 [40  6]]


Soma com broadcast (difusão) de um vetor por uma matriz:
$$\begin{aligned}
\boldsymbol{v}_1 \oplus \boldsymbol{A} &= \begin{bmatrix}5 & 3\end{bmatrix}\oplus\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}5 & 3\\ 5 & 3\\ 5 & 3\end{bmatrix}+\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
&= \begin{bmatrix}7 & 3\\ 9 & 9\\ 13 & 5\end{bmatrix}\\
\end{aligned}$$

In [78]:
print(v1 + A)

[[ 7  3]
 [ 9  9]
 [13  5]]


Cuidado com as dimensões das variáveis:

In [79]:
print("Vetor v2:")
print(v2, "dimensão:", v2.shape)
print("Matriz A:")
print(A, "dimensão:", A.shape)
try:
    v2 + A
except Exception as e:
    print(e)

Vetor v2:
[9 2 1] dimensão: (3,)
Matriz A:
[[2 0]
 [4 6]
 [8 2]] dimensão: (3, 2)
operands could not be broadcast together with shapes (3,) (3,2) 


In [80]:
print("Matriz A:")
print(A, "dimensão:", A.shape)
print("Matriz B:")
print(B, "dimensão:", B.shape)
try:
    A + B
except Exception as e:
    print(e)

Matriz A:
[[2 0]
 [4 6]
 [8 2]] dimensão: (3, 2)
Matriz B:
[[1 3]
 [5 7]] dimensão: (2, 2)
operands could not be broadcast together with shapes (3,2) (2,2) 


## Operações não-lineares

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{A ** 2} &= \begin{bmatrix}2^2 & 0^2\\ 4^2 & 6^2\\ 8^2 & 2^2\end{bmatrix}
\end{aligned}$$

In [81]:
print(A ** 2)

[[ 4  0]
 [16 36]
 [64  4]]


$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.sqrt(A)} &= \begin{bmatrix}\sqrt{2} & \sqrt{0}\\ \sqrt{4} & \sqrt{6}\\ \sqrt{8} & \sqrt{2}\end{bmatrix}\\
\mathtt{A ** 0.5} &= \begin{bmatrix}2^\frac{1}{2} & 0^\frac{1}{2}\\ 4^\frac{1}{2} & 6^\frac{1}{2}\\ 8^\frac{1}{2} & 2^\frac{1}{2}\end{bmatrix}
\end{aligned}$$

In [82]:
print(np.sqrt(A))
print(A ** 0.5)

[[1.41421356 0.        ]
 [2.         2.44948974]
 [2.82842712 1.41421356]]
[[1.41421356 0.        ]
 [2.         2.44948974]
 [2.82842712 1.41421356]]


## Operações de agregação

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A)} &= \frac{2 + 0 + 4 + 6 + 8 + 2}{2\cdot 3}\\
\mathtt{np.sum(A)} &= 2 + 0 + 4 + 6 + 8 + 2\\
\mathtt{np.prod(A)} &= 2 \cdot 0 \cdot 4 \cdot 6 \cdot 8 \cdot 2\\
\end{aligned}$$

In [83]:
np.mean(A), np.sum(A), np.prod(A)

(3.6666666666666665, 22, 0)

In [84]:
A.mean(), A.sum(), A.prod()

(3.6666666666666665, 22, 0)

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A, axis=0)} &= \frac{1}{3}\begin{bmatrix}2 + 4 + 8 & 0 + 6 + 2\end{bmatrix}\\
\mathtt{np.sum(A, axis=0)} &= \begin{bmatrix}2 + 4 + 8 & 0 + 6 + 2\end{bmatrix}\\
\mathtt{np.prod(A, axis=0)} &= \begin{bmatrix}2 \cdot 4 \cdot 8 & 0 \cdot 6 \cdot 2\end{bmatrix}\\
\end{aligned}$$

In [85]:
np.mean(A, axis=0), np.sum(A, axis=0), np.prod(A, axis=0)

(array([4.66666667, 2.66666667]), array([14,  8]), array([64,  0]))

In [86]:
A.mean(axis=0), A.sum(axis=0), A.prod(axis=0)

(array([4.66666667, 2.66666667]), array([14,  8]), array([64,  0]))

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A, axis=1)} &= \frac{1}{2}\begin{bmatrix}2 + 0 & 4 + 6 & 8 + 2\end{bmatrix}\\
\mathtt{np.sum(A, axis=1)} &= \begin{bmatrix}2 + 0 & 4 + 6 & 8 + 2\end{bmatrix}\\
\mathtt{np.prod(A, axis=1)} &= \begin{bmatrix}2 \cdot 0 & 4 \cdot 6 & 8 \cdot 2\end{bmatrix}\\
\end{aligned}$$

In [87]:
np.mean(A, axis=1), np.sum(A, axis=1), np.prod(A, axis=1)

(array([1., 5., 5.]), array([ 2, 10, 10]), array([ 0, 24, 16]))

In [88]:
A.mean(axis=1), A.sum(axis=1), A.prod(axis=1)

(array([1., 5., 5.]), array([ 2, 10, 10]), array([ 0, 24, 16]))

In [89]:
np.mean(A, axis=0, keepdims=True)

array([[4.66666667, 2.66666667]])

In [90]:
A.mean(axis=0, keepdims=True)

array([[4.66666667, 2.66666667]])

In [91]:
A - A.mean(axis=0, keepdims=True)

array([[-2.66666667, -2.66666667],
       [-0.66666667,  3.33333333],
       [ 3.33333333, -0.66666667]])

## Multiplicação de Matrizes

Para matrizes $\boldsymbol{X} \in \mathbb{R}^{a\times b}$ e $\boldsymbol{Y} \in \mathbb{R}^{b\times c}$, temos que
$\boldsymbol{XY} \in \mathbb{R}^{a\times c}$. No Numpy, essa operação é representada por $\texttt{X @ Y}$.

A multiplicação é definida por:
$$\begin{aligned}
(\boldsymbol{XY})_{ij} = \sum_k \boldsymbol{X}_{ik}\boldsymbol{Y}_{kj}
\end{aligned}$$

In [92]:
print(A @ B)
print("Dimensão de A @ B:", (A@B).shape)

[[ 2  6]
 [34 54]
 [18 38]]
Dimensão de A @ B: (3, 2)


Cuidado com as dimensões das matrizes:

In [93]:
try:
    B @ A
except Exception as e:
    print(e)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [94]:
print(A @ B @ v1)
print((A @ B) @ v1)

[ 28 332 204]
[ 28 332 204]


### Inversão de matrizes
Outra operação bastante comum é multiplicar uma matriz pela inversa dela...

Seja $\boldsymbol{B}$ uma matriz inversível, então $\boldsymbol{B}^{-1} \boldsymbol{B} = \boldsymbol{I}$


In [95]:
print(B)

[[1 3]
 [5 7]]


In [96]:
B_inv = np.linalg.inv(B)
print(B_inv)

[[-0.875  0.375]
 [ 0.625 -0.125]]


In [97]:
print(B_inv @ B)

[[1. 0.]
 [0. 1.]]


A inversa pode ser usada no produto com vetores:
$\boldsymbol{B}^{-1} \boldsymbol{v}_1$

In [98]:
print(B_inv @ v1)

[-3.25  2.75]


Porém, existe uma outra forma mais eficiente de computar a mesma coisa:

Se $\boldsymbol{B}^{-1} \boldsymbol{v}_1 = \boldsymbol{x}$, então $\boldsymbol{B} \boldsymbol{x} = \boldsymbol{v}_1$.
Ou seja, estamos resolvendo o sistema de equações lineares com coeficientes $\boldsymbol{B}$ e resultado $\boldsymbol{v}_1$

In [99]:
print(np.linalg.solve(B,v1))

[-3.25  2.75]


## Leitura de arquivos com dados

Normalmente os dados na disciplina serão recebidos no formato CSV. Isso significa que o dado é estruturado da seguinte maneira:
```
idade,pressão_sanguínea # Um cabeçalho opcional
39,144 # Dados separados por vírgulas ou outro separador
47,220
....
```

In [100]:
pressao_dataset = np.genfromtxt('./pressão.txt', delimiter=',', skip_header=1)
pressao_dataset

array([[ 39., 144.],
       [ 47., 220.],
       [ 45., 138.],
       [ 47., 145.],
       [ 65., 162.],
       [ 46., 142.],
       [ 67., 170.],
       [ 42., 124.],
       [ 67., 158.],
       [ 56., 154.],
       [ 64., 162.],
       [ 56., 150.],
       [ 59., 140.],
       [ 34., 110.],
       [ 42., 128.],
       [ 48., 130.],
       [ 45., 135.],
       [ 17., 114.],
       [ 20., 116.],
       [ 19., 124.],
       [ 36., 136.],
       [ 50., 142.],
       [ 39., 120.],
       [ 21., 120.],
       [ 44., 160.],
       [ 53., 158.],
       [ 63., 144.],
       [ 29., 130.],
       [ 25., 125.],
       [ 69., 175.]])

In [101]:
pressao_dataset.shape

(30, 2)

```
# idade, temperatura da água, comprimento
14,25,620
28,25,1315
....
```

In [102]:
peixe_dataset = np.genfromtxt('./peixe.txt', delimiter=',')
peixe_dataset

array([[  14.,   25.,  620.],
       [  28.,   25., 1315.],
       [  41.,   25., 2120.],
       [  55.,   25., 2600.],
       [  69.,   25., 3110.],
       [  83.,   25., 3535.],
       [  97.,   25., 3935.],
       [ 111.,   25., 4465.],
       [ 125.,   25., 4530.],
       [ 139.,   25., 4570.],
       [ 153.,   25., 4600.],
       [  14.,   27.,  625.],
       [  28.,   27., 1215.],
       [  41.,   27., 2110.],
       [  55.,   27., 2805.],
       [  69.,   27., 3255.],
       [  83.,   27., 4015.],
       [  97.,   27., 4315.],
       [ 111.,   27., 4495.],
       [ 125.,   27., 4535.],
       [ 139.,   27., 4600.],
       [ 153.,   27., 4600.],
       [  14.,   29.,  590.],
       [  28.,   29., 1305.],
       [  41.,   29., 2140.],
       [  55.,   29., 2890.],
       [  69.,   29., 3920.],
       [  83.,   29., 3920.],
       [  97.,   29., 4515.],
       [ 111.,   29., 4520.],
       [ 125.,   29., 4525.],
       [ 139.,   29., 4565.],
       [ 153.,   29., 4566.],
       [  

## Exercícios

### Computar a fórmula da normalização escore-Z

Dado um conjunto de dados $\boldsymbol{X} = [\boldsymbol{x}_1, \boldsymbol{x}_1, \ldots, \boldsymbol{x}_N]$, a normalização por escore-Z é dada por:
$$\tilde{\boldsymbol{x_i}} = \frac{\boldsymbol{x_i} - \boldsymbol{\mu}}{\boldsymbol{\sigma}}$$

Onde:
$$\begin{aligned}
\boldsymbol{\mu} &= \frac{1}{N}\sum_i^N \boldsymbol{x_i}\\
\boldsymbol{\sigma} &= \sqrt{\frac{1}{N-1}\sum_i^N (\boldsymbol{x_i}-\boldsymbol{\mu})^2}\\
\end{aligned}$$

A "desnormalização" pode ser feita por:
$$\boldsymbol{x_i} = \boldsymbol{\sigma}\tilde{\boldsymbol{x_i}} + \boldsymbol{\mu}$$

Use a fórmula para normalizar o conjunto de dados `peixe` sem usar nenhum `for` ou `while`.

In [133]:
# solução do professor
x = peixe_dataset.copy()
x_mean = x.mean(axis = 0)
print(x_mean)
x_std = np.sqrt(((x - x_mean) ** 2).sum(axis = 0) / (x.shape[0] - 1))
x_std1 = x.std(axis = 0, ddof=0)
x_std2 = x.std(axis = 0, ddof=1)
print(x_std)
print(x_std1)
print(x_std2)
x_scaled = (x - x_mean) / x_std

[  83.18181818   28.         3107.43181818]
[  44.52293515    2.26191933 1328.96288288]
[  44.0140849     2.23606798 1313.77423683]
[  44.52293515    2.26191933 1328.96288288]


In [134]:
x_scaled

array([[-1.55384675, -1.32630725, -1.87170902],
       [-1.23940207, -1.32630725, -1.34874483],
       [-0.94741773, -1.32630725, -0.74300933],
       [-0.63297305, -1.32630725, -0.38182543],
       [-0.31852837, -1.32630725,  0.00193247],
       [-0.0040837 , -1.32630725,  0.32173072],
       [ 0.31036098, -1.32630725,  0.6227173 ],
       [ 0.62480566, -1.32630725,  1.02152453],
       [ 0.93925034, -1.32630725,  1.07043485],
       [ 1.25369501, -1.32630725,  1.10053351],
       [ 1.56813969, -1.32630725,  1.1231075 ],
       [-1.55384675, -0.44210242, -1.86794669],
       [-1.23940207, -0.44210242, -1.42399148],
       [-0.94741773, -0.44210242, -0.75053399],
       [-0.63297305, -0.44210242, -0.2275698 ],
       [-0.31852837, -0.44210242,  0.11104011],
       [-0.0040837 , -0.44210242,  0.68291462],
       [ 0.31036098, -0.44210242,  0.90865456],
       [ 0.62480566, -0.44210242,  1.04409852],
       [ 0.93925034, -0.44210242,  1.07419718],
       [ 1.25369501, -0.44210242,  1.123

In [103]:
peixe_dataset_idade = peixe_dataset[:, [0]]
# peixe_dataset_idade
peixe_dataset_idade.shape

(44, 1)

In [104]:
peixe_idade_mean = peixe_dataset_idade.mean()

In [105]:
peixe_dataset_temp = peixe_dataset[:, [1]]
# peixe_dataset_temp
peixe_dataset_temp.shape

(44, 1)

In [106]:
peixe_temp_mean = peixe_dataset_temp.mean()

In [107]:
peixe_dataset_comprimento = peixe_dataset[:, [2]]
# peixe_dataset_comprimento
peixe_dataset_comprimento.shape

(44, 1)

In [108]:
peixe_comprimento_mean = peixe_dataset_comprimento.mean()

### Encontrar raízes de funções

Dada uma função $f$, o seguinte procedimento (método de Newton-Raphson) consegue encontrar aproximar zeros desta função:

1. Inicialize $\tilde{x}_0$ com um chute inicial e escolha uma tolerância $\epsilon$;
2. Compute: $$\tilde{x}_{t} = \tilde{x}_{t-1} - \frac{f(\tilde{x}_{t-1})}{f'(\tilde{x}_{t-1})}$$
3. Repita o passo 2 até que $f(\tilde{x}_t) \leq \epsilon$.

Implemente esse procedimento para $f(x) = x^2 - 2$, teste seu resultado computando $\tilde{x} \cdot \tilde{x}$.

In [109]:
# Escreva o código aqui

# Regressão linear via mínimos quadrados ordinários (OLS)

Como visto na aula de regressão linear, dado o seguinte problema:
$$\begin{aligned}
\hat{\boldsymbol{y}} = \boldsymbol{X}\boldsymbol{w}\\
\text{Queremos encontrar:}\\
\hat{\boldsymbol{w}} = \arg\min_{\boldsymbol{w}} ||\boldsymbol{y} - \boldsymbol{X}\boldsymbol{w}||^2
\end{aligned}$$

Como visto, sabemos que:
$$\hat{\boldsymbol{w}} = (\boldsymbol{X}^{\top}\boldsymbol{X})^{-1} \boldsymbol{X}^{\top}\boldsymbol{y}$$

Obtenha um modelo linear para predizer o comprimento de um peixe a partir de sua idade e da temperatura da água. Para isso, encontre o $\hat{\boldsymbol{w}}$ pro dataset `peixe` onde:
$$\boldsymbol{X} = [\mathbf{1}^{\top} \;,\; \mathtt{peixe\underline{}dataset[:,[0,1]}]\\
\boldsymbol{y} = \mathtt{peixe\underline{}dataset[:,[2]]}$$

Sem utilizar estrutura de repetição alguma, calcule a raíz do erro quadrático médio:
$$\mathrm{RMSE} = \sqrt{\frac{1}{n}\sum_i^n (\boldsymbol{y} - \hat{\boldsymbol{y}})^2}$$

In [163]:
# Escreva o código aqui
X = x[:,[0,1]]
y = x[:,[-1]]
X = np.hstack((np.ones((X.shape[0], 1)), X))

# w = np.linalg.inv(X.T @ X) @ X.T @ y
w = np.linalg.solve(X.T @ X, X.T @ y)

pred = X @ w
rmse = np.sqrt(((y - pred) ** 2).sum(axis = 0) / (y.shape[0]))
print(w)
print(rmse)

[[3904.26601675]
 [  26.24068177]
 [-106.41363636]]
[579.18198279]


# Regressão linear via gradiente descendente (GD)

Sendo $\alpha$ um passo de aprendizagem, $N$ o número de observações disponíveis e $t$ a iteração atual do algoritmo, os parâmetros $\boldsymbol{w}$ podem ser atualizados via algoritmo GD:

$$\boldsymbol{w}(t) = \boldsymbol{w}(t-1) + \alpha \frac{1}{N}\sum_{i=1}^{N} e_i(t-1) \boldsymbol{x}_i\\
\text{em que } e_i(t-1) = y_i - \boldsymbol{w}^{\top}(t-1)\boldsymbol{x}_i$$

Normalize os dados retirando a média e dividindo pelo desvio padrão (entrada e saída). Na predição, desfaça a normalização para computar o RMSE.

In [111]:
# Escreva o código aqui

# Regressão linear via gradiente descendente estocástico (SGD)

Sendo $\alpha$ um passo de aprendizagem, $N$ o número de observações disponíveis e $t$ a iteração atual do algoritmo, os parâmetros $\boldsymbol{w}$ podem ser atualizados via algoritmo SGD:

$$\boldsymbol{w}(t) = \boldsymbol{w}(t-1) + \alpha e_i(t-1) \boldsymbol{x}_i\\
\text{em que } e_i(t-1) = y_i - \boldsymbol{w}^{\top}(t-1)\boldsymbol{x}_i$$

Normalize os dados retirando a média e dividindo pelo desvio padrão (entrada e saída). Na predição, desfaça a normalização para computar o RMSE.

In [112]:
# Escreva o código aqui